/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface LatestCoverages {
    }
}
declare global {
    interface HTMLLatestCoveragesElement extends Components.LatestCoverages, HTMLStencilElement {
    }
    var HTMLLatestCoveragesElement: {
        prototype: HTMLLatestCoveragesElement;
        new (): HTMLLatestCoveragesElement;
    };
    interface HTMLElementTagNameMap {
        "latest-coverages": HTMLLatestCoveragesElement;
    }
}
declare namespace LocalJSX {
    interface LatestCoverages {
    }
    interface IntrinsicElements {
        "latest-coverages": LatestCoverages;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "latest-coverages": LocalJSX.LatestCoverages & JSXBase.HTMLAttributes<HTMLLatestCoveragesElement>;
        }
    }
}
