# temp query
query fetchImages($first: Int, $skip: Int) {
  allImages: allImages(first: $first, skip: $skip) {
    id
    name
  }
}

mutation updateImages($data: [ImagesUpdateInput]) {
  updateImages(data: $data) {
    id
    keywords
  }
}

query fetchPortfolios($first: Int, $skip: Int) {
  allPortfolios: allPortfolios(first: $first, skip: $skip) {
    id
    name
    coverPhoto {
      urlOriginal
    }
    photos {
      urlOriginal
    }
  }
}
